### ISSUE TITLE
Unable to run without sudo on Mac OS

### ISSUE THREAD

**Issue by lynndylanhurley** [mitsuhiko/listenfd#9] opened 2020-10-27 16:29 UTC
Trying to follow the [actix-web autoreload docs](https://actix.rs/docs/autoreload/), I get the following output when running without `sudo`:

```
❯ systemfd --no-pid -s http::8080 -- cargo watch -x run
~> socket http://127.0.0.1:8080/
[Running 'cargo run']
    Finished dev [unoptimized + debuginfo] target(s) in 0.11s
     Running `target/debug/graphite`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: InvalidInput, error: "fd 3 is not a socket" }', src/main.rs:29:61
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Panic in Arbiter thread.
[Finished running. Exit status: 101]
```

If I use `sudo` the project runs as expected, but ideally this would not be needed.

Any ideas why this command would need `sudo` access?

**Comment by mitsuhiko** [comment] 2022-01-15 22:45
I wonder if this is a recent change to how macos works. That hasn't been my experience in the past.

**Comment by mitsuhiko** [comment] 2022-01-24 08:28
I cannot reproduce this. Going to close this.

If this still happens please reopen this.

**Closed by mitsuhiko** 2022-01-24 08:28 UTC
